version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./bun_js-ts
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/myapp

  
  frontend:
    build: ./react-ts
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host

  nginx:
    image: nginx:latest
    ports:
      - "2000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  mongodb_data: